# Generated by Django 5.1.3 on 2025-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_medicine_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
